# For more info on HTTP files go to https://aka.ms/vs/httpfile
@schema=https
@hostname=localhost
@port=7237

GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities

###
GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities
Accept:application/xml

###
POST {{schema}}:/{{hostname}}:{{port}}/api/v2/cities/1/pointsofinterest
Accept: application/json
Content-Type: application/json

{
  "name": "A name for testing",
  "description": "A description for testing"
}

###

@poiid = {{createpoi.response.body.id}}

GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities/1/pointsofinterest/{{poiid}}
Accept:application/json
